# Generated by Django 5.2.7 on 2025-11-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentprofile_academic_year_studentprofile_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_donation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benefits', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.donortier'),
        ),
    ]
