# Generated by Django 5.2.11 on 2026-02-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
